Document: seetaface-open-role-zoo
Title: Debian seetaface-open-role-zoo Manual
Author: <insert document author here>
Abstract: This manual describes what seetaface-open-role-zoo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/seetaface-open-role-zoo/seetaface-open-role-zoo.sgml.gz

Format: postscript
Files: /usr/share/doc/seetaface-open-role-zoo/seetaface-open-role-zoo.ps.gz

Format: text
Files: /usr/share/doc/seetaface-open-role-zoo/seetaface-open-role-zoo.text.gz

Format: HTML
Index: /usr/share/doc/seetaface-open-role-zoo/html/index.html
Files: /usr/share/doc/seetaface-open-role-zoo/html/*.html
